apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.angular.appName }}
  labels:
    app: {{ .Values.angular.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.angular.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.angular.appName }}
    spec:
      containers:
        - name: {{ .Values.angular.appName }}
          image: {{ .Values.angular.image }}
          ports:
          - containerPort: {{ .Values.angular.containerPort }}
          volumeMounts:
            - name: my-first-angular-config-map
              mountPath: "/usr/src/app/src/assets/config"
      volumes:
        - name: my-first-angular-config-map
          configMap:
            name: my-first-angular-config-map
