apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: angular-ingress
  namespace: default
  annotations:
    # This needs to be set to enable automatic certificates
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    # The secret will be created automatically
    secretName: my-first-https-k8s-cluster-tls
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.angular.appName }}
          servicePort: {{ .Values.angular.servicePort }}