apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.angular.appName }}
  labels:
    app: {{ .Values.angular.appName }}
spec:
  type: {{ .Values.angular.type }}
  ports:
    - port: {{ .Values.angular.servicePort }}
      targetPort: {{ .Values.angular.containerPort }}
  selector:
    app: {{ .Values.angular.appName }}