apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.appName }}
  labels:
    app: {{ .Values.api.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.appName }}
    spec:
      containers:
        - name: {{ .Values.api.appName }}
          image: {{ .Values.api.image }}
          ports:
          - containerPort: {{ .Values.api.containerPort }}
          env:
          - name: ASPNET_HTTP_PORT
            value: "80"
          - name: ASPNET_HTTPS_PORT
            value: "443"
          volumeMounts:
            - name: my-first-key-config-map
              mountPath: "/etc/config/keys/"
            - name: my-first-file-config-map
              mountPath: "/etc/config/"
      volumes:
        - name: my-first-key-config-map
          configMap:
            name: my-first-key-config-map
        - name: my-first-file-config-map
          configMap:
            name: my-first-file-config-map